Create timberland.md
DiversityCorp/companies-on-blm pull request #233
Opened 2020-12-14 06:34 UTC by nycbeardo

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #209 

## Type of change

Please delete options that are not relevant.

- [x] Company data addition

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

**Test Configuration**:
* Browser: Google Chrome

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings

2020-12-14 14:32 UTC, kelseyhuse30 requested changes
Looking good, thanks for finding all the info including that additional Tweet! Just a few formatting issues to clean up, let me know if they don't seem resolvable.

Also, please remove the `.vscode/settings.json` file since those are your individual vscode settings.  You can add `.vscode` to the `.gitignore` file instead if you want, to prevent anyone from committing that folder to our repo.

2020-12-14 14:32 UTC, kelseyhuse30 commented on companies/timberland.md
> +        In 1992 we shared a message. Sadly, we bring it back today. We have the responsibility to care for our planet, ourselves + each other no matter who you are. Let’s work together for a better f
```suggestion
        In 1992 we shared a message. Sadly, we bring it back today. We have the responsibility to care for our planet, ourselves + each other no matter who you are. Let’s work together for a better future. Caring is no longer enough.
```

2020-12-14 14:32 UTC, kelseyhuse30 commented on companies/timberland.md
> +        In 1992 we shared a message. Sadly, we bring it back today. We don’t want to. We shouldn’t have to. As humans, we have the responsibility to care for our planet, ourselves, and each other—all
```suggestion
        In 1992 we shared a message. Sadly, we bring it back today. We don’t want to. We shouldn’t have to. As humans, we have the responsibility to care for our planet, ourselves, and each other—all of us, no matter who you are. Let’s work together now for a better future. Caring is no longer enough.Use your voice.
```

2020-12-14 14:32 UTC, kelseyhuse30 commented on companies/timberland.md
> +- url: https://www.instagram.com/p/CA3kcWTjUo5/
```suggestion
  - url: https://www.instagram.com/p/CA3kcWTjUo5/
```

2020-12-14 14:32 UTC, kelseyhuse30 commented on .vscode/settings.json
> +    "cSpell.ignoreWords": [
👀 what's cSpell?

2020-12-14 14:32 UTC, kelseyhuse30 commented on companies/timberland.md
> +    date_posted: 2020-05-31
```suggestion
  date_posted: 2020-05-31
```

make sure url, date_posted, type, raw_text are all vertically aligned

2020-12-14 20:34 UTC, nycbeardo commented
Wanted to know if the changes are acceptable

2020-12-16 02:41 UTC, kelseyhuse30 approved these changes
Thank you @nycbeardo ! 👏🏻 💓

2020-12-16 02:41 UTC, merged