Added additional links for google
DiversityCorp/companies-on-blm pull request #239
Opened 2020-12-26 19:36 UTC by aditya28sarin

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Company data addition
- [ ] Bug fix
- [ ] New feature

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

**Test Configuration**:
* Browser:

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings

2020-12-26 20:38 UTC, kelseyhuse30 requested changes
This looks great! The urls & display names are perfect.  One quick change needed: 
The line with `---` should be _after_ the additional_resources.  And a blank line at the end.

2020-12-27 05:40 UTC, aditya28sarin commented
I have updated the changes that you wanted ma'am.

2020-12-27 17:21 UTC, kelseyhuse30 commented on companies/google.md
>  ---
```suggestion
```

2020-12-27 17:22 UTC, kelseyhuse30 commented on companies/google.md
> +
```suggestion
```

2020-12-27 17:22 UTC, kelseyhuse30 approved these changes

2020-12-27 17:22 UTC, kelseyhuse30 commented
Thanks @aditya28sarin !

2020-12-27 17:23 UTC, merged