costco.md file created
DiversityCorp/companies-on-blm pull request #30
Opened 2020-10-12 09:20 UTC by Nimanita

2020-10-12 15:32 UTC, kelseyhuse30 requested changes
A few small updates and this is ready to go. Thank you SO MUCH for your research and finding this data for us. Your contribution is greatly appreciated. 🎉

2020-10-12 15:32 UTC, kelseyhuse30 commented on companies/costco.md
> +slug: Costco
```suggestion
slug: costco
```

Here's some documentation about slugs - https://support.squarespace.com/hc/en-us/articles/205814578-URL-slugs#toc-url-slug-formatting-tips

They should be all lowercase :)

2020-10-12 15:32 UTC, kelseyhuse30 commented on companies/costco.md
> +forbes_rank: 142
```suggestion
forbes_rank: 14
```

It looks like Costco is #14 .  I need to update this from forbes_rank to fortune_rank 🤦🏻  Sorry about that
https://fortune.com/company/costco/fortune500/

2020-10-12 16:13 UTC, Nimanita commented
Yes I will definitely make the change .Should I right forbes rank or fortune rank?

2020-10-12 19:06 UTC, kelseyhuse30 commented
> Yes I will definitely make the change .Should I write forbes rank or fortune rank?

if you don't mind changing it to `fortune_rank`, that would be fantastic.

2020-10-14 15:46 UTC, kelseyhuse30 approved these changes

2020-10-14 15:46 UTC, merged