Data contribution guide
DiversityCorp/companies-on-blm pull request #41
Opened 2020-10-14 11:53 UTC by LaChapeliere

# Description
Data contribution guide, define the format expected for contributions to the database

Useful for issues #4 and #9 

## Type of change

Documentation

# How Has This Been Tested?
NA

# Checklist:

- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

2020-10-14 15:55 UTC, LaChapeliere commented
> @LaChapeliere Can I help with testing this somehow or do you need anything else?

I don't think we can test anything before we have the database up and running. Then we can write scripts to update it using the csv files, and that'll require a lot of testing! Any language you favour for that kind of backend tasks? I can do it in Python, you'll need to ask someone else if you've picked another language.

I did have a couple of questions though. Do you want a validation step of the uploaded content in the process (checking a few fields at random maybe to make sure people are not uploading fake data)? Do you want to keep all source CSVs on the repo or delete them once they've been uploaded to the database?

2020-10-14 21:47 UTC, kelseyhuse30 commented
> > @LaChapeliere Can I help with testing this somehow or do you need anything else?
> 
> I don't think we can test anything before we have the database up and running. Then we can write scripts to update it using the csv files, and that'll require a lot of testing! Any language you favour for that kind of backend tasks? I can do it in Python, you'll need to ask someone else if you've picked another language.
> 
> I did have a couple of questions though. Do you want a validation step of the uploaded content in the process (checking a few fields at random maybe to make sure people are not uploading fake data)? Do you want to keep all source CSVs on the repo or delete them once they've been uploaded to the database?

@LaChapeliere 

1. Python sounds great to me. 🐍
2. Validation sounds good but I think it can wait for now since we will review all data in PRs in Github before uploading.  Let's handle that once we get to a point where we think we need it.
3. I'm fine with either keeping or deleting - I would pick the one that takes less time.

2020-10-25 17:49 UTC, LaChapeliere commented
I've finished the skeleton of the upload/download script, and the upload part for the basic company data.

@greendinosaur I've had to add a column and a UNIQUE contrainst manually to your scheme because I had forgotten to tell you that I had updated the diagram, but I don't think that will be a problem

@kelseyhuse30 You can start uploading the company data by using the script if you want. Your CSV need to have the exact format described in DATA_SOURCING.md. Drop any bug here so I can see if it's a code problem or a documentation problem and fix it :)

2020-10-28 17:46 UTC, LaChapeliere commented
@kelseyhuse30 All ready for you to play with it!
I remain around for bugs and questions. It shouldn't be too hard to write queries to plug the database with your webpage, but if you're stuck ping me ;)

2020-10-28 17:54 UTC, kelseyhuse30 commented
@LaChapeliere thanks so much!! I may not have time to test this out until this weekend.  I will let you know how it goes. Really appreciate your work here ⭐ 💓

2020-11-02 03:49 UTC, kelseyhuse30 requested changes
This is awesome @LaChapeliere !! I was able to follow your instructions really easily.  I didn't upload new data, but I can see how it works and trust you have tested it.

I have one recommendation:
When I first ran the Python script, it prompted me to install the `pandas` package.  I think we should set up a python virtual env and freeze the dependencies into a `requirements.txt` in the `data` folder.  Then anyone who needs to install all dependencies can simply run `pip install -r requirements.txt`.  [This tutorial](https://packaging.python.org/tutorials/installing-packages/) explains how to do it.

Otherwise this looks great.  I can merge this now and add an Issue to set up the virtual env / requirements.txt file, or let you handle it in this PR.  Either are fine with me.  Do you have a preference?

Thank you again!!! 💓

2020-11-02 03:49 UTC, kelseyhuse30 commented on data/DATA_SOURCING.md
> +This is the only table that accepts information on companies that are not in the database yet. Companies that already exist in the database will have their information updated (= overwritten), expect
```suggestion
This is the only table that accepts information on companies that are not in the database yet. Companies that already exist in the database will have their information updated (= overwritten), except for fields where the new data is `null`.
```

2020-11-03 21:53 UTC, LaChapeliere commented
@kelseyhuse30 My bad for the pandas import, I trashed the code that required pandas so I should have removed it. Since there's only one package to install now, the requirements.txt wouldn't make things any faster but I can still change to that setup if you prefer.

I do think it'd be better if someone tested the import, at least once for each table, mostly because I'd like to be sure that the doc is clear. But there's no hurry. If you prefer to merge and open issues tagging me later if things aren't working, that works for me too.

Glad I could help in any case! I don't think I'll get involved any further here because I already have too many projects that are closer to my skillsets, but I wish you'll get to see results for the work you're doing!

2020-12-24 21:03 UTC, kelseyhuse30 approved these changes

2020-12-24 21:03 UTC, merged